repos:
  # 1. Базовая гигиена и Безопасность
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace        # Убирает лишние пробелы в конце строк
      - id: end-of-file-fixer          # Добавляет пустую строку в конце файла
      - id: check-yaml                 # Проверяет синтаксис .yaml файлов
      - id: check-added-large-files    # Не дает закоммитить файлы > 500kb
      - id: detect-private-key         # Проверяет, не забыли ли вы приватный ключ

  # 2. Python (Ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  # 3. Frontend (Prettier)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [css, javascript, html]  # Форматирует фронтенд
