services:
  backend:
    # В продакшене мы используем готовый образ из реестра GitHub
    # ЗАМЕНИ: ghcr.io/твое_имя_пользователя/website_erste:latest
    image: ${DOCKER_IMAGE_BACKEND}
    container_name: pinlite-backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=False
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - LOG_LEVEL_CONSOLE=WARNING
      - LOG_LEVEL_FILE=INFO
    volumes:
      - uploads:/app/data/uploads
      - logs:/app/data/logs
    expose:
      - "8000"
    restart: always
    networks:
      - pinlite-network

  nginx:
    # === ИЗМЕНЕНО: Используем кастомный образ ===
    image: ${DOCKER_IMAGE_NGINX}
    container_name: pinlite-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # === ИЗМЕНЕНО: Убрали монтирование конфигов и статики ===
      # Они теперь внутри образа!
      
      # Оставляем только динамические данные
      - uploads:/app/media:ro
      
      # SSL и Certbot (это должно быть на хосте)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      backend:
        condition: service_started
    restart: always
    networks:
      - pinlite-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  uploads:
    driver: local
  logs:
    driver: local

networks:
  pinlite-network:
    driver: bridge