services:
  backend:
    # В продакшене мы используем готовый образ из реестра GitHub
    # ЗАМЕНИ: ghcr.io/твое_имя_пользователя/website_erste:latest
    image: ${DOCKER_IMAGE_BACKEND}
    container_name: pinlite-backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=False
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - LOG_LEVEL_CONSOLE=WARNING
      - LOG_LEVEL_FILE=INFO
      - SITE_URL=${SITE_URL}
    volumes:
      - uploads:/app/data/uploads
      - logs:/app/data/logs
      - ./backend/alembic:/app/alembic
      - ./backend/alembic.ini:/app/alembic.ini
    expose:
      - "8000"
    restart: always
    networks:
      - pinlite-network

  nginx:
    # === ИЗМЕНЕНО: Используем кастомный образ ===
    image: ${DOCKER_IMAGE_NGINX}
    container_name: pinlite-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-main.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
      - uploads:/app/media:ro
    depends_on:
      backend:
        condition: service_started
    restart: always
    networks:
      - pinlite-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  uploads:
    driver: local
  logs:
    driver: local

networks:
  pinlite-network:
    driver: bridge