name: CD Release (Deploy)

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    name: Build & Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Приводим имя репозитория к нижнему регистру (CodexDLC -> codexdlc)
      - name: Lowercase repo name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Используем переменную в нижнем регистре
          tags: ghcr.io/${{ env.REPO_LOWER }}:latest

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # Передаем имя образа как переменную окружения внутрь SSH сессии
          envs: REPO_LOWER
          script: |
            cd /opt/pinlite
            
            # Создаем .env
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # Логинимся
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Используем переданную переменную REPO_LOWER
            export DOCKER_IMAGE_BACKEND=ghcr.io/$REPO_LOWER:latest
            
            # Деплоим
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans --wait
            
            # Чистим
            docker image prune -f